{"trial_id": "1", "hyperparameters": {"space": [{"class_name": "Choice", "config": {"name": "embedding_dim", "default": 16, "conditions": [], "values": [16, 32, 64], "ordered": true}}, {"class_name": "Choice", "config": {"name": "mlp_units", "default": 32, "conditions": [], "values": [32, 64, 128], "ordered": true}}, {"class_name": "Float", "config": {"name": "lr", "default": 0.001, "conditions": [], "min_value": 0.001, "max_value": 0.01, "step": null, "sampling": "log"}}], "values": {"embedding_dim": 32, "mlp_units": 128, "lr": 0.0013752675270524027}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"C:\\Users\\Florencia\\OneDrive\\2- MASTER EN BIG DATA\\Tesis\\Tesis\\TrabajoFinal_MasterBigData\\.venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"C:\\Users\\Florencia\\OneDrive\\2- MASTER EN BIG DATA\\Tesis\\Tesis\\TrabajoFinal_MasterBigData\\.venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Florencia\\OneDrive\\2- MASTER EN BIG DATA\\Tesis\\Tesis\\TrabajoFinal_MasterBigData\\.venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Florencia\\OneDrive\\2- MASTER EN BIG DATA\\Tesis\\Tesis\\TrabajoFinal_MasterBigData\\.venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Florencia\\OneDrive\\2- MASTER EN BIG DATA\\Tesis\\Tesis\\TrabajoFinal_MasterBigData\\.venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Florencia\\OneDrive\\2- MASTER EN BIG DATA\\Tesis\\Tesis\\TrabajoFinal_MasterBigData\\.venv\\Lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\Users\\Florencia\\OneDrive\\2- MASTER EN BIG DATA\\Tesis\\Tesis\\TrabajoFinal_MasterBigData\\.venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner_utils.py\", line 76, in on_epoch_end\n    self._save_model()\n  File \"C:\\Users\\Florencia\\OneDrive\\2- MASTER EN BIG DATA\\Tesis\\Tesis\\TrabajoFinal_MasterBigData\\.venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner_utils.py\", line 86, in _save_model\n    self.model.save_weights(write_filepath)\nValueError: You are saving a model that has not yet been built. Try building the model first by calling it on some data or by using `build()`.\n"}